apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: logmux-aggregator-allow-tcp
  namespace: logmux
spec:
  podSelector:
    matchLabels:
      app: logmux-aggregator
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: kube-system
          podSelector:
            matchLabels:
              app: logmux-daemon
      ports:
        - protocol: TCP
          port: 8080