name: GitOps

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive infra/terraform

      - name: Terraform init
        run: terraform -chdir=infra/terraform init

      - name: Terraform validate
        run: terraform -chdir=infra/terraform validate

      - name: Terraform plan
        run: terraform -chdir=infra/terraform plan

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra/terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}